config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'

  get '/carts', to: 'carts#show', as: 'cart'
  delete 'carts/:id', to: 'carts#destroy', as: 'delete_cart'

  post 'line_items/:id/add', to: 'line_items#add_quantity', as: 'line_item_add'
  post 'line_items/:id/reduce', to: 'line_items#reduce_quantity', as: 'line_item_reduce'
  post 'line_items', to: 'line_items#create'
  get 'line_items/:id', to: 'line_items#show', as: 'line_item'
  delete 'line_items/:id', to: 'line_items#destroy'

  scope '/admin' do
    get '/', to: 'static_pages#admin_home'
    patch '/products/:id/restore', to: 'products#restore', as: 'product_restore'
    delete '/products', to: 'products#destroy', as: 'delete_product'
    resources :products
  end

  resources :products, only: %i[show index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  def sub_total
    sum = 0
    line_items.each do |line_item|
      sum += line_item.total_price
    end
    sum
  end
end

app/models/line_item.rb
# frozen_string_literal: true

class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  belongs_to :order, optional: true

  def total_price
    quantity * product.price
  end
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :line_items, dependent: :destroy

  mount_uploader :image, ImageUploader

  enum status: %i[active deleted]

  validates :name, presence: true, length: { minimum: 2, maximum: 500 }
  validate :image, :image_size
  validates :code, presence: true, format: { with: /[a-zA-Z0-9]+\z/ }, length: { is: 7 }
  validates :price, numericality: { greater_than_or_equal_to: 0, less_than: BigDecimal(10**8) },
    format: { with: /\A\d{1,7}(\.\d{1,2})?\z/ }
  validates :description, length: { minimum: 1, maximum: 5000 }

  def image_url
    super || default_image
  end

  private

  def image_size
    error.add(:image, 'should be less than 100 MB') if image.size > 100.megabytes
  end
end

app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagination
  PER_PAGE = 12

  protect_from_forgery with: :exception

  before_action :current_cart

  private

  def current_cart
    if session[:cart_id]
      cart = Cart.find_by(id: session[:cart_id])
      if cart.present?
        @current_cart = cart
      else
        session[:cart_id] = nil
      end
    elsif session[:cart_id].nil?
      @current_cart = Cart.create
      session[:cart_id] = @current_cart.id
    end
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/controllers/concerns/pagination.rb
# frozen_string_literal: true

module Pagination
  def max_page(products_count)
    (products_count.to_f / ApplicationController::PER_PAGE).ceil
  end

  def correct_page(page, products_count)
    max_page = max_page(products_count)

    if page > max_page
      max_page
    elsif page < 1
      1
    else
      page
    end
  end
end

app/controllers/line_items_controller.rb
# frozen_string_literal: true

class LineItemsController < ApplicationController
  def create
    chosen_product = Product.find(params[:product_id])

    if current_cart.products.include?(chosen_product)
      @line_item = @current_cart.line_items.find_by(product_id: chosen_product)
      @line_item.quantity += 1
    else
      @line_item = LineItem.new
      @line_item.cart = @current_cart
      @line_item.product = chosen_product

    end

    @line_item.save

    redirect_to products_path
  end

  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    redirect_to cart_path(@current_cart)
  end

  def add_quantity
    @line_item = LineItem.find(params[:id])
    @line_item.quantity += 1
    @line_item.save
    redirect_to cart_path(@current_cart)
  end

  def reduce_quantity
    @line_item = LineItem.find(params[:id])
    @line_item.quantity -= 1 if @line_item.quantity > 1
    @line_item.save
    redirect_to cart_path(@current_cart)
  end

  private

  def line_item_params
    params.require(:line_item).permit(:quantity, :product_id, :cart_id)
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @current_cart.line_items.each do |item|
      @order.line_items << item
      item.cart_id = nil
    end
    @order.save
    Cart.destroy(session[:cart_id])
    session[:cart_id] = nil
    redirect_to root_path
  end

  private

  def order_params
    params.require(:order).permit(:name, :email, :address, :pay_method)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product!, only: %i[show edit update restore add_to_cart]
  before_action :initialize_session

  def index
    @products = Product.paginate(page: correct_page(params[:page].to_i, Product.count), per_page: PER_PAGE)
  end

  def show; end

  def new
    @product = Product.new
  end

  def edit; end

  def update
    if @product.update product_params
      flash[:success] = 'Product updated!'
      redirect_to products_path
    else
      render :edit
    end
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:success] = 'Product created!'
      redirect_to products_path
    else
      render :new
    end
  end

  def destroy
    if request.xhr?
      params[:product_ids].each do |id|
        Product.find(id).deleted!
      end
      flash[:danger] = 'Selected products deleted!'
    else
      Product.find(params[:id]).deleted!
      flash[:danger] = 'Product deleted!'
      redirect_to products_path
    end
  end

  def restore
    @product.active!
    flash[:success] = 'Product restored!'
    redirect_to products_path
  end

  def add_to_cart
    id = params[:id].to_i

    session[:cart] << id unless session[:cart].include?(id)
    flash[:success] = "Product #{@product.name} was successfully added to the cart"
    redirect_to products_path
  end

  def remove_from_cart
    id = params[:id].to_i

    session[:cart].delete(id)
    redirect_to load_cart_path
  end

  def load_cart
    @cart = Product.find(session[:cart])
  end

  private

  def set_product!
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :image, :code, :price, :description, :remove_image)
  end

  def initialize_session
    session[:cart] ||= []
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end

  def admin_home; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def admin?
    request.path.include?('admin')
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
  def count_cart_item
    @current_cart.line_items.count
  end
end

app/helpers/line_items_helper.rb
# frozen_string_literal: true

module LineItemsHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/views/carts/show.html.haml
- if @cart.line_items.present?
  = link_to "Empty cart", delete_cart_path(@current_cart), method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure?"}
  %table.table.mb-5
    %thead
      %th
        Image
      %th 
        Name
      %th 
        Vendor code
      %th 
        Price
      %th
      %th
        Amount
      %th
      %th
        Total
    %tbody
    - @cart.line_items.each do |line_item|
      %tr
        %td
          = image_tag(line_item.product.image.url(:thumb))
        %td
          = line_item.product.name
        %td
          = line_item.product.code
        %td
          = number_to_currency(line_item.product.price)
        %td
          = link_to "+", line_item_add_path(id: line_item), method: :post, class: 'btn btn-outline-success btn-sm'
        %td
          %center
            = line_item.quantity
        %td
          = link_to "-", line_item_reduce_path(id: line_item), method: :post, class: 'btn btn-outline-danger btn-sm'
        %td
          = number_to_currency(line_item.total_price)
        %td
          = link_to 'Remove', line_item_path(line_item), method: :delete, class: 'btn btn-danger'
  .mb-5
    = link_to 'Checkout', "#", class: 'btn btn-success'
- else
  %h2
    The cart is empty

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>ProjectShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_pack_tag 'application'%>
  </head>

  <body>
    <header id="header" class="mb-3">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <ul class="navbar-nav mr-auto">
            <a class="navbar-brand" href="/">MYSHOP</a>
            <li><%= link_to 'Products', products_path, class: 'nav-link px-2 text-white'%></li>
          </ul>

          <div class="d-flex">
            <%= link_to cart_path, class: 'btn btn-secondary position-relative' do %>
              <%= image_tag('cart.png') %>
              Cart
              <% if count_cart_item > 0 %>
                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                  <%= count_cart_item %>
                <span class="visually-hidden">unread messages</span>
                </span>
              <% end %>
            <% end %>              
          </div>
        </div>
      </nav>
    </header>

    <div class="container">
      <% flash.each do |k, v| %>
        <%= tag.div v, class: "alert alert-#{k}", role: 'alert' %>
      <% end %>
      
      <%= yield %>
    </div>

    <footer class="fixed-bottom bg-dark">
      <div class="container">
        <div class="d-flex">
          <div class="footer-left mt-2 mb-2">
            <span class="text-decoration-none text-white-50" href="#">&copy; <i>koleshkos</i>
          </div>
        </div>       
      </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/pages/home.html.erb
<h1>Welcome to MY SHOP</h1>

app/views/products/_delete_product_modal.html.haml
#modal-window.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog{role: "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title Delete product
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", type: "button", class: "btn-close"}
      .modal-body
        Are you sure you want to delete the product?
      .modal-footer
        %button.btn.btn-secondary{"data-dismiss" => "modal", type: "button"} Close
        = link_to 'Delete', products_path(id: @product.id), data: {method: :delete}, class: "btn btn-danger" 

app/views/products/_delete_products_modal.html.haml
#modal-window.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog{role: "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title Delete product
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", type: "button", class: "btn-close"}
      .modal-body
        Are you sure you want to delete the product?
      .modal-footer
        %button.btn.btn-secondary{"data-dismiss" => "modal", type: "button"} Close 
        %button.btn.btn-danger{id: "btn-check-box-delete"} Delete

app/views/products/_form.html.haml
= form_with model: @product do |f|
  = f.label :name
  = f.text_field :name, class: 'form-control'
  %br
  = f.label :image
  .mb-3{style: "width: 18rem;"}
    - if @product.image?
      = image_tag @product.image.url(:thumb)
      = label_tag :remove_image do
        .form-check
          Remove image
          = f.check_box :remove_image, class: 'form-check-input'
  = f.file_field :image
  = f.hidden_field :image_cache
  %br
  = f.label :code
  = f.text_field :code, class: 'form-control'
  %br
  = f.label :price
  = f.number_field :price, step: 0.01, class: 'form-control'
  %br
  = f.label :description
  = f.text_area :description, class: 'form-control'
  %br
  = f.submit "Submit", class: 'btn btn-primary mb-5'
  = link_to 'Cancel', products_path, data: { confirm: "Are you sure?" }, class: 'btn btn-danger mb-5'

app/views/products/edit.html.haml
= render 'shared/errors', object: @product

= render 'form'

app/views/products/index.html.haml
- if admin?
  = link_to 'New Product', new_product_path, class: 'btn btn-primary btn-lg mb-3'

= will_paginate @products, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center)

- if admin?
  %button.btn.btn-secondary.btn-check-box-set{id: "btn-check-box-set", class: "btn-tool"} Checked all
  %button.btn.btn-primary.btn-check-box-reset{id: "btn-check-box-reset", class: "btn-tool"} Reset all
  %button.btn.btn-danger{"data-target" => "#modal-window", "data-toggle" => "modal", class:"btn-tool"} Delete
  = render 'delete_products_modal'

.row{class: "mt-3"}
  - @products.each do |product|
    - if admin?
      .col-sm-3.mb-5        
        = link_to product_path(product) do
          .card.text-center{style: "width: 18rem;"}
            = check_box_tag product.id, product.id
            %h5.card-header
              = product.name
            - if product.image?
              = image_tag(product.image.url(:thumb), class: 'card-img-top')
            - else
              = image_tag('no-image.jpg', class: 'card-img-top')
            .card-body
              %p.card-text
                = product.description.truncate(120)
            %ul.list-group.list-group-flush
              %li.list-group-item
                = number_to_currency(product.price)
              %li.list-group-item
                = product.code
            .card-body
              = link_to 'Edit', edit_product_path(product), class: 'btn btn-secondary'
              - if product.deleted?
                %p.status-deleted Deleted
    - else
      - if product.active?
        .col-sm-3.mb-5
          = link_to product_path(product) do
            .card.card-link.text-center{style: "width: 18rem;"}
              %h5.card-header
                = product.name
              - if product.image?
                = image_tag(product.image.url(:thumb), class: 'card-img-top')
              - else
                = image_tag('no-image.jpg', class: 'card-img-top')
              .card-body
                %p.card-text
                  = product.description.truncate(120)
              %ul.list-group.list-group-flush
                %li.list-group-item
                  = number_to_currency(product.price)
                %li.list-group-item
                  = product.code
              .card-body
                = link_to "Add to cart", line_items_path(product_id: product.id), method: :post, class: 'btn btn-success'

.mb-5
  = will_paginate @products, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center)

app/views/products/load_cart.html.haml
%center  
  %h1.mb-5
    Cart

- if @cart.present?
  %table.table.mb-5
    %thead
      %th
        Image
      %th 
        Name
      %th 
        Vendor code
      %th 
        Price
      %th
        Amount
    %tbody
    - @cart.each do |product|
      %tr
        %td
          = image_tag(product.image.url(:thumb))
        %td
          = product.name
        %td
          = product.code
        %td
          = number_to_currency(product.price)
        %td
          %input{type:'number', value: "1", min: "1"}
        %td
          = link_to 'Remove', remove_from_cart_path(product), method: :delete, class: 'btn btn-danger'
  = link_to 'Checkout', "#", class: 'btn btn-success'
- else
  %h2
    The cart is empty

app/views/products/new.html.haml
= render 'shared/errors', object: @product

%div
  = render 'form'

app/views/products/show.html.haml
%strong Name:
%br 
= @product.name
%br
%strong Image: 
%br
.image
  - if @product.image?
    = image_tag @product.image.url
  - else
    = image_tag('no-image.jpg')
%br
%strong Vendor code:
%br
= @product.code
%br
%strong Price:
%br
= number_to_currency(@product.price)
%br
%strong Description:
%br 
= @product.description
%br 

%div.mt-3.mb-5
  = link_to 'Back', products_path, class: 'btn btn-primary'
  - if admin?
    = link_to 'Edit', edit_product_path(@product), class: 'btn btn-secondary'
    - if @product.active?
      %button.btn.btn-danger{"data-target" => "#modal-window", "data-toggle" => "modal"} Destroy
      = render 'delete_product_modal'
    - else
      = link_to 'Restore', product_restore_path(@product), class: 'btn btn-success', method: :patch

app/views/shared/_errors.html.haml
- if object.errors.full_messages.any?
  .alert.alert-danger
    %ul.mb-0
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/static_pages/admin_home.html.haml
%h1 Welcome ADMIN to app MY SHOP

app/views/static_pages/home.html.haml
<h1>Welcome to MY SHOP</h1>